import fs from "fs";
import path from "path";
import { db } from "@/db";
import { siteConfig } from "@/db/schema";
import { eq } from "drizzle-orm";

export const FALLBACK_THEME_ID = "youplay";

export interface ThemeMeta {
  id: string;
  name: string;
  version: string;
  author: string;
  description: string;
  preview: string;
  authorUrl?: string;
}

export const THEME_REGISTRY: ThemeMeta[] = [
  {
    id: "youplay",
    name: "YouPlay",
    version: "1.0",
    author: "Deen Doughouz",
    description: "Modern, high-conversion responsive video theme with light & dark mode support.",
    preview: "/themes/youplay.png",
    authorUrl: "https://codecanyon.net/user/doughouzlight",
  },
];

// In test environment, register testtheme fixture if registered
if (process.env.NODE_ENV === "test") {
  THEME_REGISTRY.push({
    id: "testtheme",
    name: "Test Theme",
    version: "1.0",
    author: "Test Suite",
    description: "Test fixture theme for verifying multi-theme switching and fallback mechanisms.",
    preview: "/themes/testtheme.png",
  });
}

/**
 * Validates theme ID format: lowercase letters, digits, hyphen only.
 * Disallows directory traversal, dots, slashes.
 */
export function isValidThemeIdFormat(id: string): boolean {
  if (!id || typeof id !== "string") return false;
  return /^[a-z0-9-]+$/.test(id);
}

/**
 * Validates whether a theme exists in the registry allow-list and on the filesystem.
 */
export function isRegisteredAndExistingTheme(id: string): boolean {
  if (!isValidThemeIdFormat(id)) return false;

  const found = THEME_REGISTRY.some((t) => t.id === id);
  if (!found) return false;

  // Check themes/<id> directory on disk
  const themeDir = path.join(process.cwd(), "src", "app", "themes", id);
  if (fs.existsSync(themeDir)) return true;

  // In test environment, also allow test fixtures directory
  if (process.env.NODE_ENV === "test") {
    const fixtureDir = path.join(process.cwd(), "tests", "fixtures", "themes", id);
    if (fs.existsSync(fixtureDir)) return true;
  }

  return false;
}

// 5-second in-memory TTL cache
interface ThemeCache {
  themeId: string;
  timestamp: number;
}

let activeThemeCache: ThemeCache | null = null;
const CACHE_TTL_MS = 5000;

export function invalidateActiveThemeCache(): void {
  activeThemeCache = null;
}

/**
 * Returns the currently active theme ID.
 * 1. Checks FORCE_THEME environment variable first.
 * 2. Checks in-memory cache (5s TTL).
 * 3. Reads siteConfig.active_theme from DB.
 * 4. Validates against registry allow-list and folder existence.
 * 5. Returns FALLBACK_THEME_ID ("youplay") on failure or invalid value.
 */
export async function getActiveThemeId(): Promise<string> {
  // 1. FORCE_THEME override
  const forceEnv = process.env.FORCE_THEME;
  if (forceEnv) {
    if (isRegisteredAndExistingTheme(forceEnv)) {
      return forceEnv;
    }
  }

  const now = Date.now();
  if (activeThemeCache && now - activeThemeCache.timestamp < CACHE_TTL_MS) {
    return activeThemeCache.themeId;
  }

  let dbTheme = "";
  try {
    const [row] = await db
      .select({ value: siteConfig.value })
      .from(siteConfig)
      .where(eq(siteConfig.name, "active_theme"))
      .limit(1);

    if (row?.value) {
      dbTheme = row.value.trim().toLowerCase();
    } else {
      // Backward compatibility check for "theme"
      const [oldRow] = await db
        .select({ value: siteConfig.value })
        .from(siteConfig)
        .where(eq(siteConfig.name, "theme"))
        .limit(1);
      if (oldRow?.value) {
        dbTheme = oldRow.value.trim().toLowerCase();
      }
    }
  } catch (err) {
    console.error("[THEMES] Failed to query active_theme from DB:", err);
  }

  let resolved = FALLBACK_THEME_ID;
  if (dbTheme && isRegisteredAndExistingTheme(dbTheme)) {
    resolved = dbTheme;
  }

  activeThemeCache = {
    themeId: resolved,
    timestamp: now,
  };

  return resolved;
}

/**
 * Manifest cache & route lookup.
 * Theme route manifest is generated by scripts/generate-theme-manifest.ts.
 */
let manifestCache: Record<string, string[]> | null = null;

export function getThemeManifest(): Record<string, string[]> {
  if (manifestCache) return manifestCache;

  const manifestPath = path.join(process.cwd(), "src", "config", "theme-manifest.json");
  try {
    if (fs.existsSync(manifestPath)) {
      const raw = fs.readFileSync(manifestPath, "utf-8");
      manifestCache = JSON.parse(raw);
      return manifestCache!;
    }
  } catch (err) {
    console.error("[THEMES] Failed to read theme-manifest.json:", err);
  }

  return { [FALLBACK_THEME_ID]: [] };
}

/**
 * Normalizes pathname and checks if a theme implements the route.
 */
export function themeHasRoute(themeId: string, pathname: string): boolean {
  const manifest = getThemeManifest();
  const routes = manifest[themeId] || [];

  const clean = pathname === "" ? "/" : pathname;
  // Direct exact match
  if (routes.includes(clean)) return true;

  // Match dynamic routes, e.g. /watch/[videoId] matches /watch/abc
  for (const r of routes) {
    if (r.includes("[") && r.includes("]")) {
      const regexPattern =
        "^" +
        r
          .replace(/\[\.\.\.[^\]]+\]/g, ".*")
          .replace(/\[[^\]]+\]/g, "[^/]+") +
        "$";
      if (new RegExp(regexPattern).test(clean)) {
        return true;
      }
    }
  }

  return false;
}
